stages:
  - build
  - deploy

build-front-end-job:
  stage: build
  image: node:lts-bullseye
  variables:
    PUBLIC_URL: https://treamforce.gitlab.io/treampardy-take-2
  script:
    - cd treampardy-take-2
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - build/

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
    - mv build/ public
  artifacts:
    paths:
      - public
